import {
  CategoryInfaqIcon,
  CategoryOrtuAsuhIcon,
  CategoryUtsmaniPeduliIcon,
  CategoryWakafIcon,
} from './module-elements'

export const CATEGORY_MENU = [
  {
    title: 'Infaq/ Sedekah',
    icon: CategoryInfaqIcon,
    path: '/wakaf?category=infaq',
  },
  {
    title: 'Wakaf',
    icon: CategoryWakafIcon,
    path: '/wakaf?category=wakaf',
  },
  {
    title: 'Orangtua Asuh',
    icon: CategoryOrtuAsuhIcon,
    path: '/wakaf?category=ortu-asuh',
  },
  {
    title: 'Utsmani Peduli',
    icon: CategoryUtsmaniPeduliIcon,
    path: '/wakaf?category=utsmani-peduli',
  },
]

// export const DUMMY_DONATION_LIST: Donation[] = [
//   {
//     id: '1',
//     created_at: '2021-09-01T00:00:00.000',
//     updated_at: '2021-09-01T00:00:00.000',
//     title: 'Wakaf Masjid',
//     category: DonationCategory.WAKAF,
//     target_amount: 20_020_000_000,
//     current_amount: 5_000_000_000,
//     deadline: '2025-03-01T00:00:00.000',
//     description:
//       "<p>Pesantren Tahfizh Al-Qur'an Al-Utsmani merencanakan perluasan gedung pusat dan melanjutkan pembangunan di beberapa daerah seperti Medan, Padang, Bogor, Cirebon, Kalimantan Selatan, Sulawesi, dan Papua.</p><br><p>Biaya yang dibutuhkan adalah <strong>Rp. 20.020.000.000,- (Dua puluh miliar dua puluh juta rupiah)</strong>.</p><br><p>Kami membutuhkan 1.000.000 donatur untuk berkontribusi dalam gerakan wakaf pembangunan pesantren tahfizh Al-Qu'an sebesar Rp. 20.020,- atau kelipatannya.<p>",
//     banner: { id: 1, image_url: '/assets/images/wakaf-thumbnail.png' },
//     donor_count: 1083,
//     cp_name: 'Dr. Abdullah Rasyid S.Kom.',
//     cp_detail: "Pendiri Pesantren Tahfizh Al-Qur'an",
//     cp_wa_number: '+6285686861111',
//     cp_email: 'abdullahrasyid@gmail.com',
//   },
//   {
//     id: '2',
//     created_at: '2021-09-01T00:00:00.000',
//     updated_at: '2021-09-01T00:00:00.000',
//     title: 'Wakaf Masjid',
//     category: DonationCategory.WAKAF,
//     target_amount: 100000000,
//     current_amount: 50000000,
//     deadline: '2025-03-01T00:00:00.000',
//     description: 'Wakaf untuk membangun masjid',
//     banner: { id: 1, image_url: '/assets/images/wakaf-thumbnail.png' },
//     donor_count: 10,
//     cp_name: 'Dr. Abdullah Rasyid S.Kom.',
//     cp_detail: "Pendiri Pesantren Tahfizh Al-Qur'an",
//     cp_wa_number: '+6285686861111',
//     cp_email: 'abdullahrasyid@gmail.com',
//   },
//   {
//     id: '3',
//     created_at: '2021-09-01T00:00:00.000',
//     updated_at: '2021-09-01T00:00:00.000',
//     title: 'Wakaf Masjid',
//     category: DonationCategory.WAKAF,
//     target_amount: 100000000,
//     current_amount: 50000000,
//     deadline: '2025-03-01T00:00:00.000',
//     description: 'Wakaf untuk membangun masjid',
//     banner: { id: 1, image_url: '/assets/images/wakaf-thumbnail.png' },
//     donor_count: 10,
//     cp_name: 'Dr. Abdullah Rasyid S.Kom.',
//     cp_detail: "Pendiri Pesantren Tahfizh Al-Qur'an",
//     cp_wa_number: '+6285686861111',
//     cp_email: 'abdullahrasyid@gmail.com',
//   },
//   {
//     id: '4',
//     created_at: '2021-09-01T00:00:00.000',
//     updated_at: '2021-09-01T00:00:00.000',
//     title: 'Wakaf Masjid',
//     category: DonationCategory.WAKAF,
//     target_amount: 100000000,
//     current_amount: 50000000,
//     deadline: '2025-03-01T00:00:00.000',
//     description: 'Wakaf untuk membangun masjid',
//     banner: { id: 1, image_url: '/assets/images/wakaf-thumbnail.png' },
//     donor_count: 10,
//     cp_name: 'Dr. Abdullah Rasyid S.Kom.',
//     cp_detail: "Pendiri Pesantren Tahfizh Al-Qur'an",
//     cp_wa_number: '+6285686861111',
//     cp_email: 'abdullahrasyid@gmail.com',
//   },
// ]
